project_id = "aotzivwzoxmnnawcxioo"

[functions.create-payment]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.purchase-gift-card]
verify_jwt = true

[functions.gift-card-webhook]
verify_jwt = false

[functions.admin-create-gift-card]
verify_jwt = true
